spring:
  mvc:
    view:
      prefix:
      suffix: .jsp
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thefilm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

